# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Doom Sparkle"
license = "MIT"
licenselink = "https://github.com/russtheaerialist/doomsparkle/blob/master/LICENSE.md"
description = ""
homepage = "http://doomsparkle.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Russell Hay"
  homepage = "http://russellhay.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
