addons:
  ssh_known_hosts: russellhay.com
language: go
go:
- tip
install: go get -v github.com/spf13/hugo
script:
- mkdir -p themes/doomsparkle/static/css/
- sass themes/doomsparkle/static/scss/main.scss:themes/doomsparkle/static/css/main.css
  --style compressed
- hugo
notifications:
  email:
    on_faliure: always
before_install:
- openssl aes-256-cbc -K $encrypted_5a6c7e78736b_key -iv $encrypted_5a6c7e78736b_iv
  -in doomsparkle-deploy.enc -out doomsparkle-deploy -d
  -in doomsparkle-deploy.enc -out doomsparkle-deploy -d
- gem install sass
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/doomsparkle-deploy
- ssh-add $TRAVIS_BUILD_DIR/doomsparkle-deploy
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/seattlefilmmakers/
  on:
    branch: master
